In [7]:
import pandas as pd

import psycopg2
import io
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:2020@localhost:5432/testdb')
csv = pd.read_sql("SELECT * FROM vrp_ekz_prog ORDER BY id",engine)
s = pd.read_sql("SELECT * FROM lmin_prog_inder ORDER BY index",engine)

com = csv['o_housing_inder']
lmin_b = s['lmin']
lmin_o = s['lmin']
lmin_p = s['lmin']

a=com.shift(1)
a_b = a.loc[csv.o_script.str.match(r'базовый')].reset_index(drop = True)
a_o = a.loc[csv.o_script.str.match(r'оптимистичный')].reset_index(drop = True)
a_p = a.loc[csv.o_script.str.match(r'пессимистичный')].reset_index(drop = True)
a_b[0]= 32.12
a_o[0]= 32.12
a_p[0]= 32.12
a = a_b.append(a_o).append(a_p).reset_index(drop = True) 

Gcom = com/a*100

Gcom_b = Gcom.loc[csv.o_script.str.match(r'базовый')].reset_index(drop = True)
Gcom_o = Gcom.loc[csv.o_script.str.match(r'оптимистичный')].reset_index(drop = True)
Gcom_p = Gcom.loc[csv.o_script.str.match(r'пессимистичный')].reset_index(drop = True)
 
i=0
b=100
o=100
p=100
newdf = pd.DataFrame(columns=['lconS_b','lconS_o','lconS_p'], index=range(12))
while i<=len(Gcom_b)-1:
    b = (b*((((Gcom_b[i]-100) *  7.650956084885128) + ((lmin_b[i]-100) * 13.529047529134685)) + 100)) /100
    o = (o*((((Gcom_o[i]-100) *  7.650956084885128) + ((lmin_o[i]-100) * 13.529047529134685)) + 100)) /100
    p = (p*((((Gcom_p[i]-100) *  7.650956084885128) + ((lmin_p[i]-100) * 13.529047529134685)) + 100)) /100
    newdf.loc[i].lconS_b = b
    newdf.loc[i].lconS_o = o
    newdf.loc[i].lconS_p = p 
    i=i+1
lconS_b = newdf['lconS_b']
lconS_o = newdf['lconS_o']
lconS_p = newdf['lconS_p']
Gcom_b

0    100.933998
1    100.555213
2    100.552147
3    100.549115
4    100.546117
5    100.573325
6    100.540054
Name: o_housing_inder, dtype: float64

In [8]:
lcont_bb = lconS_b.shift(1)
lcont_bb[0] = 100
lcon_b = lconS_b/lcont_bb*100

lcont_oo = lconS_o.shift(1)
lcont_oo[0] = 100
lcon_o = lconS_o/lcont_oo*100

lcont_pp = lconS_p.shift(1)
lcont_pp[0] = 100
lcon_p = lconS_p/lcont_pp*100

new = pd.DataFrame(columns=['lcon_b','lcon_o','lcon_p'])

new.lcon_b = lcon_b
new.lcon_o = lcon_o
new.lcon_p = lcon_p

new.to_sql   ('lcon_prog_inder', engine, schema='public',if_exists='replace', index = True)
newdf.to_sql('lcons_prog_inder', engine, schema='public',if_exists='replace', index = True)

In [9]:
new

     lcon_b   lcon_o   lcon_p
0   176.202  176.202  172.629
1    146.02  161.596  138.216
2   107.724  122.823  99.9269
3    107.92  122.566  100.369
4   135.916  150.132  128.373
5   150.054  163.416  142.287
6    157.02  170.442  173.985
7       NaN      NaN      NaN
8       NaN      NaN      NaN
9       NaN      NaN      NaN
10      NaN      NaN      NaN
11      NaN      NaN      NaN