In [1]:
import pandas as pd

csv = pd.read_csv('vrp_ekz_fact.csv')
csv_p = pd.read_csv('vrp_ekz_prog.csv')

lret_csv = pd.read_csv('lret(2019-2025).csv')
lwhl_csv = pd.read_csv('lwhl(2019-2025).csv')
lagr_csv = pd.read_csv('lagr(2019-2025).csv')
lmin_csv = pd.read_csv('lmin(2019-2025).csv')
lcon_csv = pd.read_csv('lcon(2019-2025).csv')
ltrd_csv = pd.read_csv('ltrd(2001-2018).csv')
man_csv = pd.read_csv('lman, Nman(2019-2025).csv')
Ncon_csv = pd.read_csv('Ncon(2019-2025).csv')
Ntrd_csv = pd.read_csv('Ntrd(2001-2018).csv')
Nmin_csv = pd.read_csv('Nmin(2019-2025).csv')
Nret_csv = pd.read_csv('Nret(2019-2025).csv')
Nagr_csv = pd.read_csv('Nagr(2019-2025).csv')

Nret_f =   csv['o_prod_retail_makat']
Nwhl_f =    csv['o_prod_trade_makat']
Nagr_f =     csv['o_prod_agro_makat']
Nmin_f =   csv['o_prod_mining_makat']
Nman_f =      csv['o_prod_man_makat']
Ncon_f = csv['o_prod_building_makat']
Nelc_f =   csv['o_prod_energo_makat']
Nwtr_f =    csv['o_prod_water_makat']
Nind_f =    csv['o_prod_water_makat']
 
lelc_f =    csv['o_ifo_energo_makat']
lwtr_f =     csv['o_ifo_water_makat']


Ntrd_f = Ntrd_csv['0']
ltrd_f = ltrd_csv['0']

Nmin_b = Nmin_csv['Nmin_b']
Nmin_o = Nmin_csv['Nmin_o']
Nmin_p = Nmin_csv['Nmin_p']


Nman_b =  man_csv['Nman_b']
Nman_o =  man_csv['Nman_o']
Nman_p =  man_csv['Nman_p']

lman_b =  man_csv['lman_b']
lman_o =  man_csv['lman_o']
lman_p =  man_csv['lman_p']

lret_b = lret_csv['lret_b']
lret_o = lret_csv['lret_o']
lret_p = lret_csv['lret_p']

lwhl_b = lwhl_csv['lwhl_b']
lwhl_o = lwhl_csv['lwhl_o']
lwhl_p = lwhl_csv['lwhl_p']

lagr_b = lagr_csv['lagr_b']
lagr_o = lagr_csv['lagr_o']
lagr_p = lagr_csv['lagr_p']

lmin_b = lmin_csv['lmin_b']
lmin_o = lmin_csv['lmin_o']
lmin_p = lmin_csv['lmin_p']

lcon_b = lcon_csv['lcon_b']
lcon_o = lcon_csv['lcon_o']
lcon_p = lcon_csv['lcon_p']

Ncon_b = Ncon_csv['Ncon_b']
Ncon_o = Ncon_csv['Ncon_o']
Ncon_p = Ncon_csv['Ncon_p']

Nret_b = Nret_csv['Nret_b']
Nret_o = Nret_csv['Nret_o']
Nret_p = Nret_csv['Nret_p']

Nagr_b = Nagr_csv['Nagr_b']
Nagr_o = Nagr_csv['Nagr_o']
Nagr_p = Nagr_csv['Nagr_p']

inf = csv_p['o_inflation']

ltrd_b = (lret_b[0]*Nret_f[18] + lwhl_b[0]*Nwhl_f[18])/Ntrd_f[12]
lammct_b = (lagr_b[0]*Nagr_f[18] + lmin_b[0]*Nmin_f[18] + lman_b[0]*Nman_f[18] + lcon_b[0]*Ncon_f[18] + ltrd_b * Ntrd_f[18])/(Nagr_f[18]+Nmin_f[18]+Nman_f[18]+Ncon_f[18]+Ntrd_f[18])
S_b= (100*((lammct_b-100)* (-1.9748362951242386) +100 ))/100
K_b= (100*((lammct_b-100)*  0.33968756231368225  +100))/100
lelc_b= S_b/100 * 100
lwtr_b= K_b/100 * 100

Delc = inf *  0.859486933458211  + 100
Dwtr = inf *  1.1746265013388206 + 100

Delc_b = Delc.loc[csv_p.o_script.str.match(r'базовый')].reset_index(drop = True)
Dwtr_b = Dwtr.loc[csv_p.o_script.str.match(r'базовый')].reset_index(drop = True)
Delc_o = Delc.loc[csv_p.o_script.str.match(r'оптимистичный')].reset_index(drop = True)
Dwtr_o = Dwtr.loc[csv_p.o_script.str.match(r'оптимистичный')].reset_index(drop = True)
Delc_p = Delc.loc[csv_p.o_script.str.match(r'пессимистичный')].reset_index(drop = True)
Dwtr_p = Dwtr.loc[csv_p.o_script.str.match(r'пессимистичный')].reset_index(drop = True)


Nelc_b = (Nelc_f[18]*lelc_b*Delc_b[0])/10000
Nwtr_b = (Nwtr_f[18]*lwtr_b*Dwtr_b[0])/10000
Nind_b = Nmin_b[0]+Nman_b[0]+Nelc_b+Nwtr_b
Nind_f = Nmin_f+Nman_f+Nelc_f+Nwtr_f
lind_b = ((lmin_b[0]*Nmin_f[18])+(lman_b[0]*Nman_f[18])+(lelc_b*Nelc_f[18])+(lwtr_b*Nwtr_f[18]))/ Nind_f[18]
Nind_b = Nmin_b[0]+Nman_b[0]+Nelc_b+Nwtr_b
Dind_b= (Nind_b/Nind_f[18]/lind_b)*10000
Dwhl_b = inf[0] * 0.8574762712379193 + (Dind_b-100)*0.9269933771713703+100
Nwhl_b = (Nwhl_f[18]*lwhl_b[0]*Dwhl_b)/10000
Ntrd_b = Nret_b[0]+Nwhl_b
Dtrd_b = Ntrd_b/(Nret_f[18] + Nwhl_f[18])/ltrd_b *10000


ltrd_o = (lret_o[0]*Nret_f[18] + lwhl_o[0]*Nwhl_f[18])/Ntrd_f[18]
lammct_o = (lagr_o[0]*Nagr_f[18] + lmin_o[0]*Nmin_f[18] + lman_o[0]*Nman_f[18] + lcon_o[0]*Ncon_f[18] + ltrd_o * Ntrd_f[18])/(Nagr_f[18]+Nmin_f[18]+Nman_f[18]+Ncon_f[18]+Ntrd_f[18])
S_o= (100*((lammct_o-100)* (-1.9748362951242386) +100))/100
K_o= (100*((lammct_o-100)*  0.33968756231368225  +100))/100
lelc_o= S_o/100 * 100
lwtr_o= K_o/100 * 100

Nelc_o = (Nelc_f[18]*lelc_o*Delc_o[0])/10000
Nwtr_o = (Nwtr_f[18]*lwtr_o*Dwtr_o[0])/10000
Nind_o = Nmin_o[0]+Nman_o[0]+Nelc_o+Nwtr_o
Nind_f = Nmin_f+Nman_f+Nelc_f+Nwtr_f
lind_o = ((lmin_o[0]*Nmin_f[18])+(lman_o[0]*Nman_f[18])+(lelc_o*Nelc_f[18])+(lwtr_o*Nwtr_f[18]))/ Nind_f[18]
Nind_o = Nmin_o[0]+Nman_o[0]+Nelc_o+Nwtr_o
Dind_o= (Nind_o/Nind_f[18]/lind_o)*10000
Dwhl_o = inf[0] * 0.8574762712379193 + (Dind_o-100)*0.9269933771713703+100
Nwhl_o = (Nwhl_f[18]*lwhl_o[0]*Dwhl_o)/10000
Ntrd_o = Nret_o[0]+Nwhl_o
Dtrd_o = Ntrd_o/(Nret_f[18] + Nwhl_f[18])/ltrd_o *10000


ltrd_p = (lret_p[0]*Nret_f[18] + lwhl_p[0]*Nwhl_f[18])/Ntrd_f[18]
lammct_p = (lagr_p[0]*Nagr_f[18] + lmin_p[0]*Nmin_f[18] + lman_p[0]*Nman_f[18] + lcon_p[0]*Ncon_f[18] + ltrd_p * Ntrd_f[18])/(Nagr_f[18]+Nmin_f[18]+Nman_f[18]+Ncon_f[18]+Ntrd_f[18])
S_p= (100*((lammct_p-100)* (-1.9748362951242386) +100))/100
K_p= (100*((lammct_p-100)*  0.33968756231368225  +100))/100
lelc_p= S_p/100 * 100
lwtr_p= K_p/100 * 100
Nelc_p = (Nelc_f[18]*lelc_p*Delc_p[0])/10000
Nwtr_p = (Nwtr_f[18]*lwtr_p*Dwtr_p[0])/10000
Nind_p = Nmin_p[0]+Nman_p[0]+Nelc_p+Nwtr_p
Nind_f = Nmin_f+Nman_f+Nelc_f+Nwtr_f
lind_p = ((lmin_p[0]*Nmin_f[18])+(lman_p[0]*Nman_f[18])+(lelc_p*Nelc_f[18])+(lwtr_p*Nwtr_f[18]))/ Nind_f[18]
Nind_p = Nmin_p[0]+Nman_p[0]+Nelc_p+Nwtr_p
Dind_p= (Nind_p/Nind_f[18]/lind_p)*10000
Dwhl_p = inf[0] * 0.8574762712379193 + (Dind_p-100)* 0.9269933771713703 +100
Nwhl_p = (Nwhl_f[18]*lwhl_p[0]*Dwhl_p)/10000
Ntrd_p = Nret_p[0]+Nwhl_p
Dtrd_p = Ntrd_p/(Nret_f[18] + Nwhl_f[18])/ltrd_p *10000

ltrd_bb = ltrd_b
lelc_bb = lelc_b
lwtr_bb = lwtr_b
lind_bb = lind_b
Ntrd_bb = Ntrd_b
Nelc_bb = Nelc_b
Nwtr_bb = Nwtr_b
Nind_bb = Nind_b
Nwhl_bb = Nwhl_b
Dtrd_bb = Dtrd_b
Dwhl_bb = Dwhl_b
Dind_bb = Dind_b

ltrd_oo = ltrd_o
lelc_oo = lelc_o
lwtr_oo = lwtr_o
lind_oo = lind_o
Ntrd_oo = Ntrd_o
Nelc_oo = Nelc_o
Nwtr_oo = Nwtr_o
Nind_oo = Nind_o
Nwhl_oo = Nwhl_o
Dtrd_oo = Dtrd_o
Dwhl_oo = Dwhl_o
Dind_oo = Dind_o

ltrd_pp = ltrd_p
lelc_pp = lelc_p
lwtr_pp = lwtr_p
lind_pp = lind_p
Ntrd_pp = Ntrd_p
Nelc_pp = Nelc_p
Nwtr_pp = Nwtr_p
Nind_pp = Nind_p
Nwhl_pp = Nwhl_p
Dtrd_pp = Dtrd_p
Dwhl_pp = Dwhl_p
Dind_pp = Dind_p

In [2]:
ltrd_b = ltrd_bb
lelc_b = lelc_bb
lwtr_b = lwtr_bb
lind_b = lind_bb
Ntrd_b = Ntrd_bb
Nelc_b = Nelc_bb
Nwtr_b = Nwtr_bb
Nind_b = Nind_bb
Nwhl_b = Nwhl_bb
Dtrd_b = Dtrd_bb
Dwhl_b = Dwhl_bb
Dind_b = Dind_bb

i = 0

newdf_1 = pd.DataFrame(columns=['ltrd_b',
                              'lelc_b',
                              'lwtr_b',
                              'lind_b',
                              'Ntrd_b',
                              'Nelc_b',
                              'Nwtr_b',
                              'Nind_b',
                              'Nwhl_b',
                              'Dtrd_b',
                              'Delc_b',
                              'Dwtr_b',
                              'Dwhl_b',
                              'Dind_b'],index = range(12))

while i<=len(csv_p.loc[csv_p.o_script.str.match(r'базовый')].reset_index(drop = True))-2:
    
    Nind_b_p = Nmin_b[i]+Nman_b[i]+Nelc_b+Nwtr_b
    ltrd_b = (lret_b[i+1]*Nret_b[i] + lwhl_b[i+1]*Nwhl_b)/Ntrd_b
    
    lammct_b = (lagr_b[i+1]*Nagr_b[i] + lmin_b[i+1]*Nmin_b[i] + lman_b[i+1]*Nman_b[i] + lcon_b[i+1]*Ncon_b[i] + ltrd_b * Ntrd_b)/(Nagr_b[i]+Nmin_b[i]+Nman_b[i]+Ncon_b[i]+Ntrd_b) 
    
    
    
    S_b= (100*((lammct_b-100)*   (-1.9748362951242386)  +100))/100
    K_b = (100*((lammct_b-100)*   0.33968756231368225   +100))/100
    
    lelc_b= S_b/100 * 100
    lwtr_b= K_b/100 * 100
    
    Nelc_b = (Nelc_b*lelc_b*Delc_b[i+1])/10000
    Nwtr_b = (Nwtr_b*lwtr_b*Dwtr_b[i+1])/10000
    Nind_b = Nmin_b[i+1]+Nman_b[i+1]+Nelc_b+Nwtr_b
    lind_b = ((lmin_b[i+1]*Nmin_b[i])+(lman_b[i+1]*Nman_b[0])+(lelc_b*Nelc_b)+(lwtr_b*Nwtr_b))/ Nind_b
    Nind_b = Nmin_b[i+1]+Nman_b[i+1]+Nelc_b+Nwtr_b    
    Dind_b= (Nind_b/Nind_b_p/lind_b)*10000
    Dwhl_b = inf[i+1] * 0.8574762712379193 + (Dind_b-100)*0.9269933771713703+100
    
    Ntrd_b_p = Nret_b[i]+Nwhl_b
    Nwhl_b = (Nwhl_b*lwhl_b[i+1]*Dwhl_b)/10000
    Ntrd_b = Nret_b[i+1]+Nwhl_b   
    
    Dtrd_b = Ntrd_b/Ntrd_b_p/ltrd_b*10000
    
    i = i+1
    newdf_1.loc[i].ltrd_b = ltrd_b
    newdf_1.loc[i].lelc_b = lelc_b
    newdf_1.loc[i].lwtr_b = lwtr_b
    newdf_1.loc[i].lind_b = lind_b
    newdf_1.loc[i].Ntrd_b = Ntrd_b
    newdf_1.loc[i].Nelc_b = Nelc_b
    newdf_1.loc[i].Nwtr_b = Nwtr_b
    newdf_1.loc[i].Nind_b = Nind_b
    newdf_1.loc[i].Nwhl_b = Nwhl_b
    
    newdf_1.loc[i].Dtrd_b = Dtrd_b     
    newdf_1.loc[i].Dwhl_b = Dwhl_b
    newdf_1.loc[i].Dind_b = Dind_b
    
newdf_1.loc[0].ltrd_b = ltrd_bb
newdf_1.loc[0].lelc_b = lelc_bb
newdf_1.loc[0].lwtr_b = lwtr_bb
newdf_1.loc[0].lind_b = lind_bb
newdf_1.loc[0].Ntrd_b = Ntrd_bb
newdf_1.loc[0].Nelc_b = Nelc_bb
newdf_1.loc[0].Nwtr_b = Nwtr_bb
newdf_1.loc[0].Nind_b = Nind_bb
newdf_1.loc[0].Nwhl_b = Nwhl_bb
newdf_1.loc[0].Dtrd_b = Dtrd_bb
newdf_1.loc[0].Dwhl_b = Dwhl_bb
newdf_1.loc[0].Dind_b = Dind_bb

newdf_1.Delc_b = Delc_b 
newdf_1.Dwtr_b = Dwtr_b

lind_b = newdf_1['lind_b']
lelc_b = newdf_1['lelc_b']
lwtr_b = newdf_1['lwtr_b']
ltrd_b = newdf_1['ltrd_b']

Nind_b = newdf_1['Nind_b']
Nelc_b = newdf_1['Nelc_b']
Nwtr_b = newdf_1['Nwtr_b']
Ntrd_b = newdf_1['Ntrd_b']
Nwhl_b = newdf_1['Nwhl_b']

newdf_1

,ltrd_b,lelc_b,lwtr_b,lind_b,Ntrd_b,Nelc_b,Nwtr_b,Nind_b,Nwhl_b,Dtrd_b,Delc_b,Dwtr_b,Dwhl_b,Dind_b
0,119.137,91.2253,101.509,101.954,5419.4,1.91859,111.923,24595.1,2368.79,90.453,105.156922,107.047759,103.946,98.7062
1,99.8945,100.124,99.9787,96.242,5905.41,2.02004,119.786,25544.3,2664.43,109.083,105.156922,107.047759,112.482,107.915
2,96.34,105.747,99.0114,99.8495,5964.75,2.24629,126.96,24923.4,2744.4,104.842,105.156922,107.047759,103.028,97.7163
3,96.9229,104.959,99.147,99.7329,6010.25,2.45901,133.27,24352.6,2809.84,103.962,104.297435,105.873133,102.407,97.9716
4,96.0503,106.458,98.8892,99.6207,5984,2.73031,139.53,23623.6,2861.13,103.658,104.297435,105.873133,101.855,97.3759
5,93.4694,110.797,98.1429,99.4419,5750.39,3.1551,144.982,22498.3,2870.24,102.81,104.297435,105.873133,100.367,95.7709
6,102.092,96.4364,100.613,99.2702,6211.72,3.17342,154.437,22812.1,3050.74,105.809,104.297435,105.873133,106.271,102.14
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
ltrd_o = ltrd_oo
lelc_o = lelc_oo
lwtr_o = lwtr_oo
lind_o = lind_oo
Ntrd_o = Ntrd_oo
Nelc_o = Nelc_oo
Nwtr_o = Nwtr_oo
Nind_o = Nind_oo
Nwhl_o = Nwhl_oo
Dtrd_o = Dtrd_oo
Dwhl_o = Dwhl_oo
Dind_o = Dind_oo

i = 0

newdf_2 = pd.DataFrame(columns=['ltrd_o',
                              'lelc_o',
                              'lwtr_o',
                              'lind_o',
                              'Ntrd_o',
                              'Nelc_o',
                              'Nwtr_o',
                              'Nind_o',
                              'Nwhl_o',
                              'Dtrd_o',
                              'Delc_o',
                              'Dwtr_o',
                              'Dwhl_o',
                              'Dind_o'],index = range(12))

while i<=len(csv_p.loc[csv_p.o_script.str.match(r'оптимистичный')].reset_index(drop = True))-2:
    Nind_o_p = Nmin_o[i] + Nman_o[i] + Nelc_o + Nwtr_o
    ltrd_o =  (lret_o[i+1]*Nret_o[i] + lwhl_o[i+1]*Nwhl_o)/Ntrd_o
    
    lammct_o = (lagr_o[i+1]*Nagr_o[i] + lmin_o[i+1]*Nmin_o[i] + lman_o[i+1]*Nman_o[i] + lcon_o[i+1]*Ncon_o[i] + ltrd_o * Ntrd_o)/(Nagr_o[i]+Nmin_o[i]+Nman_o[i]+Ncon_o[i]+Ntrd_o) 
    
    
    
    S_o=  (100*((lammct_o-100)*  (-1.9748362951242386)  +100))/100
    K_o = (100*((lammct_o-100)*   0.33968756231368225   +100))/100
    
    lelc_o= S_o/100 * 100
    lwtr_o= K_o/100 * 100
    
    Nelc_o = (Nelc_o*lelc_o*Delc_o[i+1])/10000
    Nwtr_o = (Nwtr_o*lwtr_o*Dwtr_o[i+1])/10000
    Nind_o =   Nmin_o[i+1]+Nman_o[i+1]+Nelc_o+Nwtr_o
    lind_o = ((lmin_o[i+1]*Nmin_o[i])+(lman_o[i+1]*Nman_o[0])+(lelc_o*Nelc_o)+(lwtr_o*Nwtr_o))/ Nind_o
    Nind_o =   Nmin_o[i+1]+Nman_o[i+1]+Nelc_o+Nwtr_o    
    Dind_o=   (Nind_o/Nind_o_p/lind_o)*10000
    Dwhl_o = inf[i+1] * 0.8574762712379193 + (Dind_o-100)*0.9269933771713703 +100
    
    Ntrd_o_p = Nret_o[i]+Nwhl_o
    Nwhl_o = (Nwhl_o*lwhl_o[i+1]*Dwhl_o)/10000
    Ntrd_o = Nret_o[i+1]+Nwhl_o   
    
    Dtrd_o = Ntrd_o/Ntrd_o_p/ltrd_o*10000
    
    i = i+1
    newdf_2.loc[i].ltrd_o = ltrd_o
    newdf_2.loc[i].lelc_o = lelc_o
    newdf_2.loc[i].lwtr_o = lwtr_o
    newdf_2.loc[i].lind_o = lind_o
    newdf_2.loc[i].Ntrd_o = Ntrd_o
    newdf_2.loc[i].Nelc_o = Nelc_o
    newdf_2.loc[i].Nwtr_o = Nwtr_o
    newdf_2.loc[i].Nind_o = Nind_o
    newdf_2.loc[i].Nwhl_o = Nwhl_o
    
    newdf_2.loc[i].Dtrd_o = Dtrd_o     
    newdf_2.loc[i].Dwhl_o = Dwhl_o
    newdf_2.loc[i].Dind_o = Dind_o
    
newdf_2.loc[0].ltrd_o = ltrd_oo
newdf_2.loc[0].lelc_o = lelc_oo
newdf_2.loc[0].lwtr_o = lwtr_oo
newdf_2.loc[0].lind_o = lind_oo
newdf_2.loc[0].Ntrd_o = Ntrd_oo
newdf_2.loc[0].Nelc_o = Nelc_oo
newdf_2.loc[0].Nwtr_o = Nwtr_oo
newdf_2.loc[0].Nind_o = Nind_oo
newdf_2.loc[0].Nwhl_o = Nwhl_oo
newdf_2.loc[0].Dtrd_o = Dtrd_oo
newdf_2.loc[0].Dwhl_o = Dwhl_oo
newdf_2.loc[0].Dind_o = Dind_oo
    
newdf_2.Delc_o = Delc_o 
newdf_2.Dwtr_o = Dwtr_o

lind_o = newdf_2['lind_o']
lelc_o = newdf_2['lelc_o']
lwtr_o = newdf_2['lwtr_o']
ltrd_o = newdf_2['ltrd_o']

Nind_o = newdf_2['Nind_o']
Nelc_o = newdf_2['Nelc_o']
Nwtr_o = newdf_2['Nwtr_o']
Ntrd_o = newdf_2['Ntrd_o']
Nwhl_o = newdf_2['Nwhl_o']

newdf_2

,ltrd_o,lelc_o,lwtr_o,lind_o,Ntrd_o,Nelc_o,Nwtr_o,Nind_o,Nwhl_o,Dtrd_o,Delc_o,Dwtr_o,Dwhl_o,Dind_o
0,102.305,96.2123,100.652,101.951,5368.06,2.02348,110.978,23988.9,2317.45,104.337,105.156922,107.047759,101.693,96.2761
1,112.721,80.0733,103.428,81.752,7757.27,1.69853,122.359,32033.5,3800.71,128.199,104.830317,106.601401,163.862,163.341
2,96.4715,105.811,99.0004,99.7169,7820.33,1.88405,129.132,31209.1,3914.27,104.5,104.830317,106.601401,103.016,97.703
3,99.0638,101.49,99.7436,99.6221,8091.96,1.98805,135.791,30979.6,4068.78,104.451,103.970830,105.426774,103.955,99.6412
4,109.808,82.793,102.96,99.6791,9614.44,1.71133,147.397,33461.8,4562.03,108.202,103.970830,105.426774,112.037,108.36
5,93.6766,110.388,98.2131,99.871,9232.15,1.96412,152.619,31914.2,4565.11,102.506,103.970830,105.426774,100.114,95.498
6,103.346,94.1832,101.001,99.7494,10098.5,1.92332,162.511,32699.6,4877.12,105.843,103.970830,105.426774,106.807,102.718
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ltrd_p = ltrd_pp
lelc_p = lelc_pp
lwtr_p = lwtr_pp
lind_p = lind_pp
Ntrd_p = Ntrd_pp
Nelc_p = Nelc_pp
Nwtr_p = Nwtr_pp
Nind_p = Nind_pp
Nwhl_p = Nwhl_pp
Dtrd_p = Dtrd_pp
Dwhl_p = Dwhl_pp
Dind_p = Dind_pp

i = 0

newdf_3 = pd.DataFrame(columns=['ltrd_p',
                              'lelc_p',
                              'lwtr_p',
                              'lind_p',
                              'Ntrd_p',
                              'Nelc_p',
                              'Nwtr_p',
                              'Nind_p',
                              'Nwhl_p',
                              'Dtrd_p',
                              'Delc_p',
                              'Dwtr_p',
                              'Dwhl_p',
                              'Dind_p'],index = range(12))

while i<=len(csv_p.loc[csv_p.o_script.str.match(r'пессимистичный')].reset_index(drop = True))-2:
    Nind_p_p = Nmin_p[i] + Nman_p[i] + Nelc_p + Nwtr_p
    ltrd_p =  (lret_p[i+1]*Nret_p[i] + lwhl_p[i+1]*Nwhl_p)/Ntrd_p
    
    lammct_p = (lagr_p[i+1]*Nagr_p[i] + lmin_p[i+1]*Nmin_p[i] + lman_p[i+1]*Nman_p[i] + lcon_p[i+1]*Ncon_p[i] + ltrd_p * Ntrd_p)/(Nagr_p[i]+Nmin_p[i]+Nman_p[i]+Ncon_p[i]+Ntrd_p) 
    
    
    
    S_p=  (100*((lammct_p-100)*  (-1.9748362951242386)  +100))/100
    K_p = (100*((lammct_p-100)*   0.33968756231368225   +100))/100
    
    lelc_p= S_p/100 * 100
    lwtr_p= K_p/100 * 100
    
    Nelc_p = (Nelc_p*lelc_p*Delc_p[i+1])/10000
    Nwtr_p = (Nwtr_p*lwtr_p*Dwtr_p[i+1])/10000
    Nind_p =   Nmin_p[i+1]+Nman_p[i+1]+Nelc_p+Nwtr_p
    lind_p = ((lmin_p[i+1]*Nmin_p[i])+(lman_p[i+1]*Nman_p[0])+(lelc_p*Nelc_p)+(lwtr_p*Nwtr_p))/ Nind_p
    Nind_p =   Nmin_p[i+1]+Nman_p[i+1]+Nelc_p+Nwtr_p    
    Dind_p=   (Nind_p/Nind_p_p/lind_p)*10000
    Dwhl_p = inf[i+1] * 0.8574762712379193 + (Dind_p-100)*0.9269933771713703 +100
    
    Ntrd_p_p = Nret_p[i]+Nwhl_p
    Nwhl_p = (Nwhl_p*lwhl_p[i+1]*Dwhl_p)/10000
    Ntrd_p = Nret_p[i+1]+Nwhl_p
    
    Dtrd_p = Ntrd_p/Ntrd_p_p/ltrd_p*10000
    
    i = i+1
    newdf_3.loc[i].ltrd_p = ltrd_p
    newdf_3.loc[i].lelc_p = lelc_p
    newdf_3.loc[i].lwtr_p = lwtr_p
    newdf_3.loc[i].lind_p = lind_p
    newdf_3.loc[i].Ntrd_p = Ntrd_p
    newdf_3.loc[i].Nelc_p = Nelc_p
    newdf_3.loc[i].Nwtr_p = Nwtr_p
    newdf_3.loc[i].Nind_p = Nind_p
    newdf_3.loc[i].Nwhl_p = Nwhl_p
    
    newdf_3.loc[i].Dtrd_p = Dtrd_p     
    newdf_3.loc[i].Dwhl_p = Dwhl_p
    newdf_3.loc[i].Dind_p = Dind_p
    
newdf_3.loc[0].ltrd_p = ltrd_pp
newdf_3.loc[0].lelc_p = lelc_pp
newdf_3.loc[0].lwtr_p = lwtr_pp
newdf_3.loc[0].lind_p = lind_pp
newdf_3.loc[0].Ntrd_p = Ntrd_pp
newdf_3.loc[0].Nelc_p = Nelc_pp
newdf_3.loc[0].Nwtr_p = Nwtr_pp
newdf_3.loc[0].Nind_p = Nind_pp
newdf_3.loc[0].Nwhl_p = Nwhl_pp
newdf_3.loc[0].Dtrd_p = Dtrd_pp
newdf_3.loc[0].Dwhl_p = Dwhl_pp
newdf_3.loc[0].Dind_p = Dind_pp

newdf_3.Delc_p = Delc_p 
newdf_3.Dwtr_p = Dwtr_p

lind_p = newdf_3['lind_p']
lelc_p = newdf_3['lelc_p']
lwtr_p = newdf_3['lwtr_p']
ltrd_p = newdf_3['ltrd_p']

Nind_p = newdf_3['Nind_p']
Nelc_p = newdf_3['Nelc_p']
Nwtr_p = newdf_3['Nwtr_p']
Ntrd_p = newdf_3['Ntrd_p']
Nwhl_p = newdf_3['Nwhl_p']

newdf_3

,ltrd_p,lelc_p,lwtr_p,lind_p,Ntrd_p,Nelc_p,Nwtr_p,Nind_p,Nwhl_p,Dtrd_p,Delc_p,Dwtr_p,Dwhl_p,Dind_p
0,102.305,109.161,98.4243,94.5547,4906.92,2.3247,110.356,16685.9,1808.94,95.374,106.480531,108.856684,79.3789,72.2048
1,95.7879,106.037,98.9615,99.9934,4988.36,2.6248,118.882,16297.4,1862.59,106.13,106.480531,108.856684,102.992,97.6781
2,95.2933,106.915,98.8105,99.8751,5001.82,2.96405,126.492,15800.8,1907.34,105.222,105.621045,107.682057,102.432,97.0739
3,86.9714,119.364,96.6693,99.6638,4455.58,3.73688,131.672,14429.8,1839.65,102.424,105.621045,107.682057,96.5299,91.6315
4,92.4497,111.509,98.0204,99.1455,4290.54,4.40117,138.981,13739.7,1850.04,104.16,105.621045,107.682057,100.615,96.0381
5,101.704,97.4395,100.44,98.9263,4650.97,4.52954,150.316,13842.5,1961.17,106.585,105.621045,107.682057,105.995,101.842
6,141.95,34.4346,111.278,87.6473,8236.62,1.64016,179.057,20463.1,3302.79,124.759,105.156922,107.047759,167.937,168.662
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
newdf.to_csv(r'Расчет по Оптовой торговле, Электро и Водоснабжению.csv')

Nind.to_csv(r'Nind_Makat(2019-2025).csv',index=False)
Nelc.to_csv(r'Nelc_Makat(2019-2025).csv',index=False)
Nwtr.to_csv(r'Nwtr_Makat(2019-2025).csv',index=False)
Ntrd.to_csv(r'Ntrd_Makat(2019-2025).csv',index=False)
Nwhl.to_csv(r'Nwhl_Makat(2019-2025).csv',index=False)

lind.to_csv(r'lind_Makat(2019-2025).csv',index=False)
lelc.to_csv(r'lelc_Makat(2019-2025).csv',index=False)
lwtr.to_csv(r'lwtr_Makat(2019-2025).csv',index=False)
ltrd.to_csv(r'ltrd_Makat(2019-2025).csv',index=False)