In [7]:
import pandas as pd
csv = pd.read_csv('vrp_ekz_fact.csv')
c = pd.read_csv('vrp_ekz_prog.csv')

q = pd.read_csv('lagrt(2019-2025).csv')
w = pd.read_csv('lmint(2019-2025).csv')
d = pd.read_csv('Dmin(2019-2025).csv')
e = pd.read_csv('Nagr(2019-2025).csv')
r = pd.read_csv('Nmin(2019-2025).csv')

Nmin_p = r['c1']
Nagr_p = e['c1']

Dmin = d['0']

lagr = q['c1']
lmin = w['c1']

Nagr = csv['o_prod_agro_zhylyoi']
Nmin = csv['o_prod_mining_zhylyoi']
lman= csv['o_ifo_man_zhylyoi']
Nman = csv['o_prod_man_zhylyoi']

year = c['o_year']

lamml_2019 = (lagr[0]*Nagr[18]+lmin[0]*Nmin[18]+lman[18]*Nman[17])/(Nagr[18]+Nmin[18]+Nman[17])

lmanS_2019 = 100*((lamml_2019 - 100) * 0.8964035297804896 + 100)/100

lman_2019 = lmanS_2019/100 * 100

In [8]:
Nman_2019=(Nman[18]*lman_2019*Dmin[0])/10000
Nman_2019

323513.49308998755

In [9]:
lamml_2020 = (lagr[1]*Nagr_p[0]+lmin[1]*Nmin_p[0]+lman_2019*Nman[18])/(Nagr_p[0]+Nmin_p[0]+ Nman[18])

lmanS_2020 = lmanS_2019 *((lamml_2020 - 100) * 0.8964035297804896 + 100)/100

lman_2020 = lmanS_2020/lmanS_2019 * 100
lmanS_2019

103.57905443549427

In [10]:
Nman_2020=(Nman_2019*lman_2020*Dmin[1])/10000
Nman_2020

339666.6993956286

In [11]:
i=0
Nman_2019 = 323558.56018356624;
lman_2020 = 103.20749017188413;

lamml_2020 = 103.5781766417961;


lmanS_2020 = 106.90134242664325;
lmanS_2021 = 106.90134242664325;

newdf = pd.DataFrame(columns=['Nman','lman','lmanS', 'lamml','year'], index=range(21))

while i<=18:
    lamml_2020 = (lagr[i+2]*Nagr_p[i+1]+lmin[i+2]*Nmin_p[i+1]+lman_2020*Nman_2019)/(Nagr_p[i+1]+Nmin_p[i+1]+Nman_2019)
    
    lmanS_2021 = lmanS_2020*((lamml_2020 - 100) * 0.8964035297804896 + 100)/100        
    
    Nman_2019 = Nman_2019*lman_2020*Dmin[i+1]/10000    
    lman_2020 = lmanS_2021/lmanS_2020 * 100
    lmanS_2020=lmanS_2021
    
    newdf.loc[i+1].Nman = Nman_2019
    newdf.loc[i+2].lman = lman_2020
    newdf.loc[i+2].lmanS = lmanS_2021
    newdf.loc[i+2].lamml = lamml_2020  
    i=i+1
    
newdf.year = year

Nma = newdf['Nman']

n=(345169*85.0518*Dmin[20])/10000

Nma[0] = 323513.49308998755
Nma[20] = n
Nman = Nma

lma = newdf['lman']
lma[0] = 103.57905443549427
lma[1] = 103.20749017188413
lman = lma

lmaS = newdf['lmanS']
lmaS[0] = 103.57905443549427
lmaS[1] = 106.90134242664325
lmanS = lmaS

lamm = newdf['lamml']
lamm[0] = 103.99268222021695
lamm[1] = 103.5781766417961
lamml = lamm

newdf

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

      Nman     lman    lmanS    lamml  year
0   323513  103.579  103.579  103.993  2019
1   347612  103.207  106.901  103.578  2020
2   357458  102.832  109.929   103.16  2021
3   366738  102.596  112.783  102.896  2022
4   420076  114.544  129.186  116.225  2023
5   446504  106.291  137.314  107.018  2024
6   455913  102.107  140.207  102.351  2025
7   338027  77.1791  108.211  74.5418  2019
8   428119  102.611  111.036  102.912  2020
9   439379   102.63  113.956  102.934  2021
10  457535  104.132  118.665   104.61  2022
11  586210  128.124  152.038  131.374  2023
12  623624  106.382  161.741   107.12  2024
13  642846  103.082  166.726  103.438  2025
14  296157  65.0443  108.446  61.0045  2020
15  293674  99.1618  107.537   99.065  2021
16  298439  101.622  109.282   101.81  2022
17  320183  107.286  117.244  108.128  2023
18  340130   106.23  124.548   106.95  2024
19  345169  101.481  126.393  101.653  2025
20  335822  85.0518    107.5  83.3242  2019

In [38]:
newdf.to_csv (r'lman, Nman(2019-2025).csv', index = False)