In [1]:
import pandas as pd

import psycopg2
import io
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:2020@localhost:5432/testdb')
csv_p = pd.read_sql('SELECT * FROM vrp_prognoz_inder ORDER BY index',engine)


csv   = pd.read_sql('SELECT * FROM lgds_prog_inder ORDER BY index',engine)
csv_n = pd.read_sql('SELECT * FROM ngds_prog_inder ORDER BY index',engine)

lgds =   csv['lgds_inder']
Ngds = csv_n['Ngds_inder']

Ngds_pp = Ngds.shift(1)

Ngds_pp_b = Ngds_pp.loc[csv_p.prognoz.str.match(r'базовый')].reset_index(drop = True)
Ngds_pp_o = Ngds_pp.loc[csv_p.prognoz.str.match(r'оптимистичный')].reset_index(drop = True)
Ngds_pp_p = Ngds_pp.loc[csv_p.prognoz.str.match(r'пессимистичный')].reset_index(drop = True)
Ngds_pp_b[0]= 11330.2
Ngds_pp_o[0]= 11330.2
Ngds_pp_p[0]= 11330.2
Ngds_pp = Ngds_pp_b.append(Ngds_pp_o).append(Ngds_pp_p).reset_index(drop = True) 

n = Ngds/Ngds_pp/lgds * 10000

Dgds = pd.DataFrame(columns=['Dgds_inder'])
Dgds.Dgds_inder = n

Dgds.to_sql('dgds_prog_inder', engine, schema='public',if_exists='replace', index = True)

In [2]:
Dgds

    Dgds_inder
0   104.594029
1   106.621623
2   106.566069
3   106.342397
4   106.720294
5   106.895360
6   106.859601
7   104.178112
8   111.394767
9   107.632709
10  107.239986
11  107.313132
12  107.067283
13  106.490951
14  101.465895
15  107.070347
16  106.817312
17  107.332615
18  107.685663
19  107.904328
20  107.887659