In [21]:
import pandas as pd

csv = pd.read_csv('Dmin(2019-2025).csv')
Dmin=csv['0']

Dman = (Dmin-100)*1.0415526245421316+100

Dman

0      98.590458
1     104.160655
2     100.000000
3     100.000000
4     100.000000
5     100.000000
6     100.000000
7      96.003104
8     123.804871
9     100.000000
10    100.000000
11    100.000000
12    100.000000
13    100.000000
14     70.361487
15    100.000000
16    100.000000
17    100.000000
18    100.000000
19    100.000000
20    114.621709
Name: 0, dtype: float64

In [20]:
import pandas as pd
csv = pd.read_csv('vrp_ekz_fact.csv')
c = pd.read_csv('vrp_ekz_prog.csv')

q = pd.read_csv('lagr(2019-2025).csv')
w = pd.read_csv('lmin(2019-2025).csv')
d = pd.read_csv('Dmin(2019-2025).csv')
e = pd.read_csv('Nagrt(2019-2025).csv')
r = pd.read_csv('Nmin(2019-2025).csv')

Dmin = d['0']

lagr = q['c1']
lmin = w['c1']

Nagr = csv['o_prod_agro_kurmangazy']
Nmin = csv['o_prod_mining_kurmangazy']
lman= csv['o_ifo_man_kurmangazy']
Nman = csv['o_prod_man_kurmangazy']

Nmin_p = r['c1']
Nagr_p = e['c1']


lamml_2019 = (lagr[0]*Nagr[18]+lmin[0]*Nmin[18]+lman[18]*Nman[17])/(Nagr[18]+Nmin[18]+Nman[17])

lmanS_2019 = 100*((lamml_2019 - 100) * 2.24278451713285 + 100)/100
lman_2019 = lmanS_2019/100 * 100

Nman_2019=(Nman[18]*lman_2019*Dman[0])/10000


lamml_2020 = (lagr[1]*Nagr_p[0]+lmin[1]*Nmin_p[0]+lman_2019*Nman[18])/(Nagr_p[0]+Nmin_p[0]+ Nman[18])
lmanS_2020 = lmanS_2019 *((lamml_2020 - 100) * 2.24278451713285 + 100)/100
lman_2020 = lmanS_2020/lmanS_2019 * 100

Nman_2020=(Nman_2019*lman_2020*Dman[1])/10000
lmanS_2020

117.89931005028905

In [37]:
i=0

newdf = pd.DataFrame(columns=['Nman','lman','lmanS', 'lamml'], index=range(7))

while i<=4:
    lamml_2020 = (lagr[i+2]*Nagr_p[i+1]+lmin[i+2]*Nmin_p[i+1]+lman_2020*Nman_2019)/(Nagr_p[i+1]+Nmin_p[i+1]+Nman_2019)
    
    lmanS_2021 = lmanS_2020*((lamml_2020 - 100) * 3.330216964833216 + 100)/100        
    
    Nman_2019 = Nman_2019*lman_2020*Dman[i+1]/10000
    
    lman_2020 = lmanS_2021/lmanS_2020 * 100
    lmanS_2020=lmanS_2021
    
    newdf.loc[i+1].Nman = Nman_2019
    newdf.loc[i+2].lman = lman_2020
    newdf.loc[i+2].lmanS = lmanS_2021
    newdf.loc[i+2].lamml = lamml_2020  
    i=i+1

n=(Nman[5]*lman[6]*Dman[6])/10000

Nma = newdf['Nman']
Nma[0] = 1566.3915387104603
Nma[6] = n
Nman = Nma

lma = newdf['lman']
lma[0] = 104.18269818946997
lma[1] = 113.16592111664608
lman = lma

lmaS = newdf['lmanS']
lmaS[0] = 104.18269818946997
lmaS[1] = 117.89931005028905
lmanS = lmaS

lamm = newdf['lamml']
lamm[0] = 101.86495767093001
lamm[1] = 105.87034599894476
lamml = lamm

newdf

      Nman     lman    lmanS    lamml
0  785.164  90.4168  90.4168  97.1224
1  885.752  108.219  97.8479  102.468
2  1025.62  115.791  113.299  104.742
3   1215.8  118.543  134.308  105.568
4  1476.98  121.482   163.16  106.451
5  1799.33  121.825   198.77  106.554
6   11.946  124.537  247.543  107.368

In [38]:
newdf.to_csv(r'lman, Nman(2019-2025).csv', index = False)