In [1]:
import pandas as pd

csv = pd.read_csv('Dmin(2019-2025).csv')
Dmin=csv['0']

Dman = (Dmin-100)*0.9959132598371605+100

Dman

0      98.900391
1     103.245801
2     100.000000
3     100.000000
4     100.000000
5     100.000000
6     100.000000
7      96.881951
8     118.570599
9     100.000000
10    100.000000
11    100.000000
12    100.000000
13    100.000000
14     76.878474
15    100.000000
16    100.000000
17    100.000000
18    100.000000
19    100.000000
20    111.406653
Name: 0, dtype: float64

In [2]:

import pandas as pd
csv = pd.read_csv('vrp_ekz_fact.csv')
c = pd.read_csv('vrp_ekz_prog.csv')

q = pd.read_csv('lagrt(2019-2025).csv')
w = pd.read_csv('lmin(20019-2025).csv')
d = pd.read_csv('Dmin(2019-2025).csv')
e = pd.read_csv('Nagrt(2019-2025).csv')
r = pd.read_csv('Nmin(20019-2025).csv')

Dmin = d['0']

lagr = q['c1']
lmin = w['lmin']

Nagr = csv['o_prod_agro_inder']
Nmin = csv['o_prod_mining_inder']
lman= csv['o_ifo_man_inder']
Nman = csv['o_prod_man_inder']

Nmin_p = r['c1']
Nagr_p = e['c1']


lamml_2019 = (lagr[0]*Nagr[18]+lmin[0]*Nmin[18]+lman[18]*Nman[17])/(Nagr[18]+Nmin[18]+Nman[17])

lmanS_2019 = 100*((lamml_2019 - 100) * 1.0196078488207092 + 100)/100
lman_2019 = lmanS_2019/100 * 100

Nman_2019=(Nman[18]*lman_2019*Dman[0])/10000


lamml_2020 = (lagr[1]*Nagr_p[0]+lmin[1]*Nmin_p[0]+lman_2019*Nman[18])/(Nagr_p[0]+Nmin_p[0]+ Nman[18])
lmanS_2020 = lmanS_2019 *((lamml_2020 - 100) * 1.0196078488207092 + 100)/100
lman_2020 = lmanS_2020/lmanS_2019 * 100

Nman_2020=(Nman_2019*lman_2020*Dman[1])/10000
Nman_2019

1537.9976147517793

In [3]:
i=0
newdf = pd.DataFrame(columns=['Nman','lman','lmanS', 'lamml'], index=range(7))

while i<=4:
    lamml_2020 = (lagr[i+2]*Nagr_p[i+1]+lmin[i+2]*Nmin_p[i+1]+lman_2020*Nman_2019)/(Nagr_p[i+1]+Nmin_p[i+1]+Nman_2019)
    
    lmanS_2021 = lmanS_2020*((lamml_2020 - 100) * 0.8964035297804896 + 100)/100        
    
    Nman_2019 = Nman_2019*lman_2020*Dman[i+1]/10000
    
    lman_2020 = lmanS_2021/lmanS_2020 * 100
    lmanS_2020=lmanS_2021
    
    newdf.loc[i+1].Nman = Nman_2019
    newdf.loc[i+2].lman = lman_2020
    newdf.loc[i+2].lmanS = lmanS_2021
    newdf.loc[i+2].lamml = lamml_2020  
    i=i+1

n=(2118.97*105.765*Dmin[6])/10000

Nma = newdf['Nman']
Nma[0] = 1537.9274447849973
Nma[6] = n
Nman = Nma

lma = newdf['lman']
lma[0] = 104.01990641773855
lma[1] = 106.27241301946762
lman = lma

lmaS = newdf['lmanS']
lmaS[0] = 104.01990641773855
lmaS[1] = 110.54446457072282
lmanS = lmaS

lamm = newdf['lamml']
lamm[0] = 103.94260050311304
lamm[1] = 106.15178965787914
lamml = lamm

newdf

      Nman     lman    lmanS    lamml
0  1537.93   104.02   104.02  103.943
1  1687.52  106.272  110.544  106.152
2  1784.93  105.773  116.926   106.44
3  1886.89  105.712  123.605  106.372
4  1994.91  105.725   130.68  106.386
5  2109.56  105.747  138.191  106.412
6  2241.13  105.765  146.159  106.432

In [4]:

newdf.to_csv(r'lman, Nman(2019-2025).csv', index = False)