In [17]:
import pandas as pd

csv = pd.read_csv('Dmin(2019-2025).csv')
Dmin=csv['0']

Dman = (Dmin-100)*0.9684154806046421+100

Dman

0      98.682535
1     103.888866
2     100.000000
3     100.000000
4     100.000000
5     100.000000
6     100.000000
7      96.264196
8     122.249848
9     100.000000
10    100.000000
11    100.000000
12    100.000000
13    100.000000
14     72.297585
15    100.000000
16    100.000000
17    100.000000
18    100.000000
19    100.000000
20    113.666564
Name: 0, dtype: float64

In [18]:
import pandas as pd
csv = pd.read_csv('vrp_ekz_fact.csv')
c = pd.read_csv('vrp_ekz_prog.csv')

q = pd.read_csv('lagr(2019-2025).csv')
w = pd.read_csv('lmin(2019-2025).csv')
d = pd.read_csv('Dmin(2019-2025).csv')
e = pd.read_csv('Nagrt(2019-2025).csv')
r = pd.read_csv('Nmin(2019-2025).csv')

Dmin = d['0']

lagr = q['c1']
lmin = w['c1']

Nagr = csv['o_prod_agro_kzylkoga']
Nmin = csv['o_prod_mining_kzylkoga']
lman= csv['o_ifo_man_kzylkoga']
Nman = csv['o_prod_man_kzylkoga']

Nmin_p = r['c1']
Nagr_p = e['c1']


lamml_2019 = (lagr[0]*Nagr[18]+lmin[0]*Nmin[18]+lman[18]*Nman[17])/(Nagr[18]+Nmin[18]+Nman[17])

lmanS_2019 = 100*((lamml_2019 - 100) * 1.2910463804516183 + 100)/100
lman_2019 = lmanS_2019/100 * 100

Nman_2019=(Nman[18]*lman_2019*Dman[0])/10000


lamml_2020 = (lagr[1]*Nagr_p[0]+lmin[1]*Nmin_p[0]+lman_2019*Nman[18])/(Nagr_p[0]+Nmin_p[0]+ Nman[18])
lmanS_2020 = lmanS_2019 *((lamml_2020 - 100) * 1.2910463804516183 + 100)/100
lman_2020 = lmanS_2020/lmanS_2019 * 100

Nman_2020=(Nman_2019*lman_2020*Dman[1])/10000
Nman_2020

267.35105142595035

In [19]:
i=0

newdf = pd.DataFrame(columns=['Nman','lman','lmanS', 'lamml'], index=range(7))

while i<=4:
    lamml_2020 = (lagr[i+2]*Nagr_p[i+1]+lmin[i+2]*Nmin_p[i+1]+lman_2020*Nman_2019)/(Nagr_p[i+1]+Nmin_p[i+1]+Nman_2019)
    
    lmanS_2021 = lmanS_2020*((lamml_2020 - 100) * 1.2910463804516183 + 100)/100        
    
    Nman_2019 = Nman_2019*lman_2020*Dman[i+1]/10000
    
    lman_2020 = lmanS_2021/lmanS_2020 * 100
    lmanS_2020=lmanS_2021
    
    newdf.loc[i+1].Nman = Nman_2019
    newdf.loc[i+2].lman = lman_2020
    newdf.loc[i+2].lmanS = lmanS_2021
    newdf.loc[i+2].lamml = lamml_2020  
    i=i+1
Nma = newdf['Nman']
Nma[0] = 249.45192937121902
Nma[6] = n
Nman = Nma

lma = newdf['lman']
lma[0] = 88.07743841395136
lma[1] = 103.16348949357858
lman = lma

lmaS = newdf['lmanS']
lmaS[0] = 88.07743841395136
lmaS[1] = 90.86375892438986
lmanS = lmaS

lamm = newdf['lamml']
lamm[0] = 90.76519498712507
lamm[1] = 102.45032985760898
lamml = lamm

Nma = newdf['Nman']
Nma[0] = 249.45192937121902
n=(Nman[5]*lman[6]*Dman[6])/10000
Nma[6] = n
Nman = Nma

newdf

      Nman     lman    lmanS    lamml
0  249.452  88.0774  88.0774  90.7652
1  267.351  103.163  90.8638   102.45
2  255.561  95.5902  86.8568  96.5843
3  258.792  101.264  87.9547  100.979
4  279.246  107.904  94.9064  106.122
5  276.827  99.1338  94.0843  99.3291
6  291.183  105.186  98.9633  104.017

In [20]:
newdf.to_csv(r'lman, Nman(2019-2025).csv', index = False)