In [5]:
import pandas as pd
a = pd.read_csv('Расчет по Оптовой торговле, Электро и Водоснабжению.csv')
a

,ltrd,lelc,lwtr,lind,Ntrd,Nelc,Nwtr,Nind,Nwhl,Delc,Dwtr,Dwhl,Dind
0,104.798471,101.043676,101.043676,104.214091,26306.075991,1303.548600,18716.106221,6.495978e+06,2429.567236,105.658010,107.037205,104.033499,98.636337
1,103.644661,100.237945,100.237945,96.078389,29330.777038,1380.580733,20080.864972,6.826466e+06,2871.782721,105.658010,107.037205,113.297480,109.376928
2,103.272079,100.778114,100.778114,99.650507,32445.522227,1470.044439,21661.244534,7.042011e+06,3229.222106,105.658010,107.037205,108.245133,103.519274
3,102.934891,100.714262,100.714262,99.519778,35391.607436,1550.352206,23095.324358,7.245885e+06,3584.435089,104.715008,105.864338,107.266754,103.391628
4,102.642765,103.985131,103.985131,99.486383,38923.167888,1688.148103,25424.065133,8.417709e+06,4391.993577,104.715008,105.864338,118.807616,116.772019
5,102.375235,101.596072,101.596072,99.415136,42378.548129,1795.958894,27344.601130,8.962465e+06,4987.827189,104.715008,105.864338,110.463517,107.097931
6,102.132235,100.533183,100.533183,99.338647,45852.985195,1890.665757,29102.527737,9.155907e+06,5460.659459,104.715008,105.864338,106.789657,102.838485