In [30]:
import pandas as pd

csv = pd.read_csv('Dmin(2019-2025).csv')
Dmin=csv['0']

Dman = (Dmin-100)*1.1387036451379635+100

Dman

0      98.496660
1     104.437527
2     100.000000
3     100.000000
4     100.000000
5     100.000000
6     100.000000
7      95.737129
8     125.388972
9     100.000000
10    100.000000
11    100.000000
12    100.000000
13    100.000000
14     68.389184
15    100.000000
16    100.000000
17    100.000000
18    100.000000
19    100.000000
20    115.594715
Name: 0, dtype: float64

In [31]:
import pandas as pd
csv = pd.read_csv('vrp_ekz_fact.csv')
c = pd.read_csv('vrp_ekz_prog.csv')

q = pd.read_csv('lagr(2019-2025).csv')
w = pd.read_csv('lmin(2019-2025).csv')
d = pd.read_csv('Dmin(2019-2025).csv')
e = pd.read_csv('Nagrt(2019-2025).csv')
r = pd.read_csv('Nmin(2019-2025).csv')

Dmin = d['0']

lagr = q['c1']
lmin = w['c1']

Nagr = csv['o_prod_agro_isatai']
Nmin = csv['o_prod_mining_isatai']
lman= csv['o_ifo_man_isatai']
Nman = csv['o_prod_man_isatai']

Nmin_p = r['c1']
Nagr_p = e['c1']


lamml_2019 = (lagr[0]*Nagr[18]+lmin[0]*Nmin[18]+lman[18]*Nman[17])/(Nagr[18]+Nmin[18]+Nman[17])

lmanS_2019 = 100*((lamml_2019 - 100) * 3.330216964833216 + 100)/100
lman_2019 = lmanS_2019/100 * 100

Nman_2019=(Nman[18]*lman_2019*Dman[0])/10000


lamml_2020 = (lagr[1]*Nagr_p[0]+lmin[1]*Nmin_p[0]+lman_2019*Nman[18])/(Nagr_p[0]+Nmin_p[0]+ Nman[18])
lmanS_2020 = lmanS_2019 *((lamml_2020 - 100) * 3.330216964833216 + 100)/100
lman_2020 = lmanS_2020/lmanS_2019 * 100

Nman_2020=(Nman_2019*lman_2020*Dman[1])/10000

lamml_2020

97.16643083711571

In [33]:
i=0
newdf = pd.DataFrame(columns=['Nman','lman','lmanS', 'lamml'], index=range(7))

while i<=4:
    lamml_2020 = (lagr[i+2]*Nagr_p[i+1]+lmin[i+2]*Nmin_p[i+1]+lman_2020*Nman_2019)/(Nagr_p[i+1]+Nmin_p[i+1]+Nman_2019)
    
    lmanS_2021 = lmanS_2020*((lamml_2020 - 100) * 3.330216964833216 + 100)/100        
    
    Nman_2019 = Nman_2019*lman_2020*Dman[i+1]/10000
    
    lman_2020 = lmanS_2021/lmanS_2020 * 100
    lmanS_2020=lmanS_2021
    
    newdf.loc[i+1].Nman = Nman_2019
    newdf.loc[i+2].lman = lman_2020
    newdf.loc[i+2].lmanS = lmanS_2021
    newdf.loc[i+2].lamml = lamml_2020  
    i=i+1

n=(635.262*107.249*Dman[6])/10000

Nma = newdf['Nman']
Nma[0] = 776.9696329860055
Nma[6] = n
Nman = Nma

lma = newdf['lman']
lma[0] = 89.63959194571754
lma[1] = 90.5635999027345
lman = lma

lmaS = newdf['lmanS']
lmaS[0] = 89.63959194571754
lmaS[1] = 81.18084140416344
lmanS = lmaS

lamm = newdf['lamml']
lamm[0] = 96.88896904805681
lamm[1] = 97.16643083711571
lamml = lamm

newdf

      Nman     lman    lmanS    lamml
0   776.97  89.6396  89.6396   96.889
1  711.549  90.5636  81.1808  97.1664
2  707.868  99.4827  74.8747  99.8447
3  621.846  87.8477  65.7757  96.3509
4   627.56  100.919  66.3801  100.276
5  620.309  98.8446  65.6131   99.653
6  681.312  107.253  70.3719  102.178

In [37]:
newdf.to_csv(r'lman, Nman(2019-2025).csv', index = False)