In [8]:
import pandas as pd

csv = pd.read_csv('Dmin(2019-2025).csv')
Dmin=csv['0']

Dman = (Dmin-100)*1.1015008204018604+100

Dman

0      98.587130
1     104.170478
2     100.000000
3     100.000000
4     100.000000
5     100.000000
6     100.000000
7      95.993668
8     123.861068
9     100.000000
10    100.000000
11    100.000000
12    100.000000
13    100.000000
14     70.291518
15    100.000000
16    100.000000
17    100.000000
18    100.000000
19    100.000000
20    114.656227
Name: 0, dtype: float64

In [9]:
import pandas as pd
csv = pd.read_csv('vrp_ekz_fact.csv')
c = pd.read_csv('vrp_ekz_prog.csv')

q = pd.read_csv('lagrt(2019-2025).csv')
w = pd.read_csv('lmin(2019-2025).csv')
d = pd.read_csv('Dmin(2019-2025).csv')
e = pd.read_csv('Nagr(2019-2025).csv')
r = pd.read_csv('Nmin(2019-2025).csv')

Nmin_p = r['c1']
Nagr_p = e['c1']

Dmin = d['0']

lagr = q['c1']
lmin = w['c1']

Nagr = csv['o_prod_agro_atyrau']
Nmin = csv['o_prod_mining_atyrau']
lman= csv['o_ifo_man_atyrau']
Nman = csv['o_prod_man_atyrau']

year = c['o_year']

lamml_2019 = (lagr[0]*Nagr[18]+lmin[0]*Nmin[18]+lman[18]*Nman[17])/(Nagr[18]+Nmin[18]+Nman[17])

lmanS_2019 = 100*((lamml_2019 - 100) * 0.7531100122842695 + 100)/100
lman_2019 = lmanS_2019/100 * 100

Nman_2019=(Nman[18]*lman_2019*Dman[0])/10000


lamml_2020 = (lagr[1]*Nagr_p[0]+lmin[1]*Nmin_p[0]+lman_2019*Nman[18])/(Nagr_p[0]+Nmin_p[0]+ Nman[18])
lmanS_2020 = lmanS_2019 *((lamml_2020 - 100) * 0.7531100122842695 + 100)/100
lman_2020 = lmanS_2020/lmanS_2019 * 100

Nman_2020=(Nman_2019*lman_2020*Dmin[1])/10000

Nman_2019

271391.8920366358

In [10]:
i=0
Nman_2019 = 271750.2882833618;

lman_2020 = 106.68701254175939;

lamml_2020 = 108.87919750459419;

lmanS_2020 = 111.79349977172471;

newdf = pd.DataFrame(columns=['Nman','lman','lmanS', 'lamml','year'], index=range(21))

while i<=18:
    lamml_2020 = (lagr[i+2]*Nagr_p[i+1]+lmin[i+2]*Nmin_p[i+1]+lman_2020*Nman_2019)/(Nagr_p[i+1]+Nmin_p[i+1]+Nman_2019)
    
    lmanS_2021 = lmanS_2020*((lamml_2020 - 100) * 0.8964035297804896 + 100)/100        
    
    Nman_2019 = Nman_2019*lman_2020*Dman[i+1]/10000
    
    lman_2020 = lmanS_2021/lmanS_2020 * 100
    lmanS_2020=lmanS_2021
    
    newdf.loc[i+1].Nman = Nman_2019
    newdf.loc[i+2].lman = lman_2020
    newdf.loc[i+2].lmanS = lmanS_2021
    newdf.loc[i+2].lamml = lamml_2020  
    i=i+1
    
newdf.year = year

n=(255007*97.2083*Dmin[20])/10000

Nma = newdf['Nman']
Nma[0] = 271750.2882833618
Nma[20] = n
Nman = Nma

lma = newdf['lman']
lma[0] = 104.78641880422563
lma[1] = 106.68701254175939
lman = lma

lmaS = newdf['lmanS']
lmaS[0] = 104.78641880422563
lmaS[1] = 111.79349977172471
lmanS = lmaS

lamm = newdf['lamml']
lamm[0] = 106.35553734003332
lamm[1] = 108.87919750459419
lamml = lamm

newdf

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

      Nman     lman    lmanS    lamml  year
0   271750  104.786  104.786  106.356  2019
1   302013  106.687  111.793  108.879  2020
2   309823  102.586  114.684  102.885  2021
3   314232  101.423  116.316  101.587  2022
4   316474  100.714  117.146  100.796  2023
5   315535  99.7032  116.799  99.6689  2024
6   315643  100.034  116.839  100.038  2025
7   287121  94.7603  110.717  94.1547  2019
8   372071  104.623  115.835  105.157  2020
9   378103  101.621  117.713  101.808  2021
10  384768  101.763  119.788  101.967  2022
11  407040  105.788  126.721  106.457  2023
12  414301  101.784  128.982   101.99  2024
13  419768   101.32  130.684  101.472  2025
14  274262  92.9508  121.472  92.1362  2020
15  264927  96.5963  117.337  96.2029  2021
16  261714   98.787  115.914  98.6468  2022
17  254749  97.3389   112.83  97.0314  2023
18  251056  98.5502  111.194  98.3827  2024
19  250061  99.6035  110.753  99.5577  2025
20  280871  97.1913  107.642  96.8667  2019

In [11]:
newdf.to_csv(r'lman, Nman(2019-2025).csv', index = False)