In [5]:
import pandas as pd

import psycopg2
import io
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:2020@localhost:5432/testdb')

csv = pd.read_sql('SELECT * FROM vrp_prognoz_kurmangazy ORDER BY index',engine)


Nagr = csv['Nagr_kurmangazy']
Ncon = csv['Ncon_kurmangazy']
Nind = csv['Nind_kurmangazy']

n = Nind + Ncon + Nagr
Ngds = pd.DataFrame(columns=['Ngds_kurmangazy'])

Ngds.Ngds_kurmangazy = n

Ngds.to_sql('ngds_prog_kurmangazy', engine, schema='public',if_exists='replace', index = True)

In [7]:
Ngds

    Ngds_kurmangazy
0      54985.914414
1      59968.216963
2      62867.313189
3      66504.415595
4      75111.486001
5      79238.682255
6      84260.452393
7      54219.628632
8      68582.331866
9      71511.399802
10     76064.722722
11     92145.649567
12     96671.217444
13    102683.611018
14     46934.553600
15     50058.514104
16     53610.047599
17     59208.721689
18     63697.320718
19     68954.425171
20     59518.732545